**1**

In [1]:
import numpy as np
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**2**

In [2]:
y = np.zeros(10)
y[4] = 1
y

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**3**

In [3]:
z = np.zeros((3,3))
k= 0
for i in range(0,len(z)):
    for j in range (0,len(z)):
        z[i][j] = k
        k += 1
z

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

**4**

In [4]:
c = np.random.random((3,3,3))
c

array([[[0.30176571, 0.18049774, 0.00188178],
        [0.05935116, 0.29773451, 0.92035294],
        [0.7864413 , 0.52776935, 0.82437209]],

       [[0.62427086, 0.41063652, 0.86009035],
        [0.21885559, 0.68821437, 0.43149067],
        [0.16168229, 0.24522605, 0.07122996]],

       [[0.79503024, 0.6976219 , 0.93036947],
        [0.46016142, 0.24012509, 0.434143  ],
        [0.86755638, 0.71481063, 0.99783335]]])

**5**

In [5]:
d = np.random.random((5,3))
e = np.random.random((3,2))
pro = np.dot(d,e)
pro

array([[0.81739634, 0.44329836],
       [0.57802958, 0.79803844],
       [0.77320704, 1.34108825],
       [0.36729388, 0.24486539],
       [1.11295859, 1.3900351 ]])

**6**

In [6]:
f = np.zeros((5,5))
for i in range(0,len(f)):
    for j in range(0,len(f)):
        f[i][j] = j
        j += 1
f

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

**7**

In [67]:
rand = np.random.random((4,4))
avg = rand.mean(axis=1)   
avg - rand

array([[-0.24694916,  0.35368936,  0.36258219,  0.21515127],
       [-0.56669141,  0.21379808, -0.15566405,  0.11792673],
       [-0.42732104,  0.10878311,  0.17872186, -0.21994091],
       [ 0.0999853 ,  0.09486709,  0.16824271, -0.29718113]])

**8**

In [77]:
x = np.random.random((4,4))
y = np.random.random((4,4))
pr = np.dot(x,y)
print(pr)
pr.diagonal(0)

[[1.41707386 0.8128084  0.58916135 0.47016262]
 [1.28684209 0.775859   0.39942946 0.71445598]
 [1.19467034 1.10405999 0.69866233 0.39157413]
 [0.9118114  0.37482164 0.23835197 0.72251602]]


array([1.41707386, 0.775859  , 0.69866233, 0.72251602])

**9**

In [114]:
from scipy.stats import mode
print(mode(x))

ModeResult(mode=array([1]), count=array([4]))


**10**

In [125]:
v = np.random.random((10))
print(v)
np.sort(v)

[0.82995854 0.33581634 0.42952511 0.18781826 0.26766179 0.36369124
 0.4247663  0.9175943  0.08565016 0.93889004]


array([0.08565016, 0.18781826, 0.26766179, 0.33581634, 0.36369124,
       0.4247663 , 0.42952511, 0.82995854, 0.9175943 , 0.93889004])

## Pandas

In [7]:
import pandas as pd

**1 , 2**

In [8]:
chipo = pd.read_csv(r'C:\Users\lenovo\Documents\GitHub\MSIT_ML_CLASS\datasets\chipotle.txt',sep = "\t")
chipo.head(10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                NaN     $1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

**3**

In [9]:
chipo.order_id.count()

4622

**4**

In [10]:
len(chipo.columns)

5

**5**

In [11]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

**7,8**

In [12]:
x = chipo.groupby('item_name')['quantity'].count()
#print(x)
print(x.idxmax()," has been ordered the most")

Chicken Bowl  has been ordered the most


In [13]:
y = pd.DataFrame(chipo.groupby('item_name')['quantity'].count())
row = y.loc[y['quantity'].idxmax()]
print('Chicken bowl was ordered in ',row['quantity'],' nos.')

Chicken bowl was ordered in  726  nos.


**9**

In [14]:
chipo.head(10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                NaN     $1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

In [15]:
most_choice_desc = chipo.groupby('choice_description')['item_name'].count()
print(most_choice_desc.idxmax(),' is the popular choice')

[Diet Coke]  is the popular choice


**10**

In [16]:
print(chipo.quantity.sum(),' items were ordered in total')

4972  items were ordered in total


**11,12**

In [25]:
#type(chipo.iloc[0]['item_price'])
#float(chipo.iloc[0]['item_price'][1:])
#for i in range(0,len(chipo)):
 #   chipo.iloc[i]['iteb

In [18]:
chipo.head(10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                NaN     $1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

In [19]:
chipo.item_price = chipo.item_price.str.replace('$','0')

In [20]:
chipo.head(10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     02.39   
1                                       [Clementine]     03.39   
2                                            [Apple]     03.39   
3                                                NaN     02.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    016.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    010.98   
6                                                NaN     01.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    011.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     09.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     09.25

In [24]:
chipo['item_price'] = chipo['item_price'].astype('float64')
type(chipo.iloc[0][-1])

numpy.float64

**13**

In [26]:
print("$",chipo.item_price.sum()," is the total revnue for the period")

$ 34500.16  is the total revnue for the period


**14**

In [40]:
arr = pd.unique(chipo.item_name)
print(len(arr)," different items were sold")

50  different items were sold


**15**

In [42]:
arr_order_id = pd.unique(chipo.order_id)
print(len(arr_order_id)," orders were made during the period")

1834  orders were made during the period


**16**

In [56]:
group_by = chipo.groupby('order_id')['item_price'].sum()
print('$',group_by.mean()," is the average amount spent per order.")

$ 18.81142857142869  is the average amount spent per order.
